/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import DTOS.peliculaDTO;
import Persistencia.añadirPeliculaDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class PanelPeliculaActualizar extends javax.swing.JPanel {

    private añadirPeliculaDAO peliculaDAO;
    private peliculaDTO peliculaActualCargada;

    /**
     * Creates new form PanelPeliculaActualizar
     */
    public PanelPeliculaActualizar() {
        initComponents();
        peliculaDAO = new añadirPeliculaDAO();

        habilitarCamposEdicion(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtIdPelicula = new javax.swing.JTextField();
        txtTituloPelicula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAnioEstreno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPaisOrigen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIdProductora = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        BntActualizar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("id de la pelicula:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("titulo pelicula :");

        txtTituloPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloPeliculaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("año estreno:");

        txtAnioEstreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioEstrenoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("pais origen: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("id de la productora:");

        txtIdProductora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoraActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnBuscar.setText("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        BntActualizar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BntActualizar.setText("Actualizar");
        BntActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(TxtIdPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(txtTituloPelicula)
                            .addComponent(txtAnioEstreno)
                            .addComponent(txtPaisOrigen))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BntActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtIdProductora, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(TxtIdPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(BntActualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtTituloPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAnioEstreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtPaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtIdProductora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnioEstrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioEstrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioEstrenoActionPerformed

    private void txtIdProductoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoraActionPerformed

    private void txtTituloPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloPeliculaActionPerformed
    private void limpiarCamposEdicion() {
        txtTituloPelicula.setText("");
        txtAnioEstreno.setText("");
        txtPaisOrigen.setText("");
        txtIdProductora.setText("");
        peliculaActualCargada = null;
    }

    private void habilitarCamposEdicion(boolean habilitar) {
        txtTituloPelicula.setEnabled(habilitar);
        txtAnioEstreno.setEnabled(habilitar);
        txtPaisOrigen.setEnabled(habilitar);
        txtIdProductora.setEnabled(habilitar);

        if (BntActualizar != null) {
            BntActualizar.setEnabled(habilitar);
        }

        if (!habilitar) {
            limpiarCamposEdicion();
            TxtIdPelicula.setText("");
        }
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String idstr = TxtIdPelicula.getText().trim();
        if (idstr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID de película para buscar.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            int idPelicula = Integer.parseInt(idstr);
            peliculaActualCargada = peliculaDAO.obtenerPeliculaPorID(idPelicula); // Usar el método del DAO

            if (peliculaActualCargada != null) {
                txtTituloPelicula.setText(peliculaActualCargada.getTitulo());
                txtAnioEstreno.setText(String.valueOf(peliculaActualCargada.getAnioEstreno()));
                txtPaisOrigen.setText(peliculaActualCargada.getPaisOrigen());
                txtIdProductora.setText(String.valueOf(peliculaActualCargada.getIdProductora()));
                habilitarCamposEdicion(true);
                JOptionPane.showMessageDialog(this, "Película encontrada. Puede editar los datos.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Película no encontrada con el ID: " + idPelicula, "No Encontrada", JOptionPane.ERROR_MESSAGE);
                habilitarCamposEdicion(false); // Limpia y deshabilita
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de la película debe ser un número entero.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            habilitarCamposEdicion(false); // Limpia y deshabilita
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar la película: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            habilitarCamposEdicion(false); // Limpia y deshabilita
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void BntActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntActualizarActionPerformed
        if (peliculaActualCargada == null) {
            JOptionPane.showMessageDialog(this, "Primero debe buscar y cargar una película.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String titulo = txtTituloPelicula.getText().trim();
        String anioStr = txtAnioEstreno.getText().trim();
        String pais = txtPaisOrigen.getText().trim();
        String idProductoraStr = txtIdProductora.getText().trim();
        
        if (titulo.isEmpty() || anioStr.isEmpty() || pais.isEmpty() || idProductoraStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos (Título, Año, País, ID Productora) son obligatorios.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            int anioEstreno = Integer.parseInt(anioStr);
            int idProductora = Integer.parseInt(idProductoraStr);
            
            peliculaDTO peliculaModificada = new peliculaDTO(
                    peliculaActualCargada.getIdPelicula(), 
                    titulo,
                    anioEstreno, 
                    pais,
                    idProductora);
            
            boolean exito = peliculaDAO.actualizarPelicula(peliculaModificada);
            
            if (exito) {
                JOptionPane.showMessageDialog(this, "Película actualizada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                habilitarCamposEdicion(false);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar la película. Verifique los datos o la consola.", "Error de Actualización", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El año de estreno y el ID de productora deben ser números enteros.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar la película: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_BntActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntActualizar;
    private javax.swing.JTextField TxtIdPelicula;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAnioEstreno;
    private javax.swing.JTextField txtIdProductora;
    private javax.swing.JTextField txtPaisOrigen;
    private javax.swing.JTextField txtTituloPelicula;
    // End of variables declaration//GEN-END:variables
}
